export const arabCountries = [
  {
    alpha2: "SA",
    alpha3: "SAU",
    countryCallingCodes: ["+966"],
    currencies: ["SAR"],
    ioc: "KSA",
    languages: ["ar"],
    name: "Saudi Arabia",
    arabicName: "السعودية",
    status: "assigned",
  },
  {
    alpha2: "EG",
    alpha3: "EGY",
    countryCallingCodes: ["+20"],
    currencies: ["EGP"],
    ioc: "EGY",
    languages: ["ar"],
    name: "Egypt",
    arabicName: "مصر",
    status: "assigned",
  },
  {
    alpha2: "AE",
    alpha3: "ARE",
    countryCallingCodes: ["+971"],
    currencies: ["AED"],
    ioc: "UAE",
    languages: ["ar"],
    name: "United Arab Emirates",
    arabicName: "الإمارات",
    status: "assigned",
  },
  {
    alpha2: "IQ",
    alpha3: "IRQ",
    countryCallingCodes: ["+964"],
    currencies: ["IQD"],
    ioc: "IRQ",
    languages: ["ar"],
    name: "Iraq",
    arabicName: "العراق",
    status: "assigned",
  },
  {
    alpha2: "JO",
    alpha3: "JOR",
    countryCallingCodes: ["+962"],
    currencies: ["JOD"],
    ioc: "JOR",
    languages: ["ar"],
    name: "Jordan",
    arabicName: "الأردن",
    status: "assigned",
  },
  {
    alpha2: "KW",
    alpha3: "KWT",
    countryCallingCodes: ["+965"],
    currencies: ["KWD"],
    ioc: "KUW",
    languages: ["ar"],
    name: "Kuwait",
    arabicName: "الكويت",
    status: "assigned",
  },
  {
    alpha2: "LB",
    alpha3: "LBN",
    countryCallingCodes: ["+961"],
    currencies: ["LBP"],
    ioc: "LBN",
    languages: ["ar"],
    name: "Lebanon",
    arabicName: "لبنان",
    status: "assigned",
  },
  {
    alpha2: "MA",
    alpha3: "MAR",
    countryCallingCodes: ["+212"],
    currencies: ["MAD"],
    ioc: "MAR",
    languages: ["ar"],
    name: "Morocco",
    arabicName: "المغرب",
    status: "assigned",
  },
  {
    alpha2: "OM",
    alpha3: "OMN",
    countryCallingCodes: ["+968"],
    currencies: ["OMR"],
    ioc: "OMA",
    languages: ["ar"],
    name: "Oman",
    arabicName: "عُمان",
    status: "assigned",
  },
  {
    alpha2: "QA",
    alpha3: "QAT",
    countryCallingCodes: ["+974"],
    currencies: ["QAR"],
    ioc: "QAT",
    languages: ["ar"],
    name: "Qatar",
    arabicName: "قطر",
    status: "assigned",
  },
  {
    alpha2: "SY",
    alpha3: "SYR",
    countryCallingCodes: ["+963"],
    currencies: ["SYP"],
    ioc: "SYR",
    languages: ["ar"],
    name: "Syria",
    arabicName: "سوريا",
    status: "assigned",
  },
  {
    alpha2: "TN",
    alpha3: "TUN",
    countryCallingCodes: ["+216"],
    currencies: ["TND"],
    ioc: "TUN",
    languages: ["ar"],
    name: "Tunisia",
    arabicName: "تونس",
    status: "assigned",
  },
  {
    alpha2: "YE",
    alpha3: "YEM",
    countryCallingCodes: ["+967"],
    currencies: ["YER"],
    ioc: "YEM",
    languages: ["ar"],
    name: "Yemen",
    arabicName: "اليمن",
    status: "assigned",
  },
  {
    alpha2: "DZ",
    alpha3: "DZA",
    countryCallingCodes: ["+213"],
    currencies: ["DZD"],
    ioc: "ALG",
    languages: ["ar"],
    name: "Algeria",
    arabicName: "الجزائر",
    status: "assigned",
  },
  {
    alpha2: "SD",
    alpha3: "SDN",
    countryCallingCodes: ["+249"],
    currencies: ["SDG"],
    ioc: "SUD",
    languages: ["ar"],
    name: "Sudan",
    arabicName: "السودان",
    status: "assigned",
  },
  {
    alpha2: "LY",
    alpha3: "LBY",
    countryCallingCodes: ["+218"],
    currencies: ["LYD"],
    ioc: "LBA",
    languages: ["ar"],
    name: "Libya",
    arabicName: "ليبيا",
    status: "assigned",
  },
  {
    alpha2: "PS",
    alpha3: "PSE",
    countryCallingCodes: ["+970"],
    currencies: [],
    ioc: "PLE",
    languages: ["ar"],
    name: "Palestine",
    arabicName: "فلسطين",
    status: "assigned",
  },
  {
    alpha2: "BH",
    alpha3: "BHR",
    countryCallingCodes: ["+973"],
    currencies: ["BHD"],
    ioc: "BHR",
    languages: ["ar"],
    name: "Bahrain",
    arabicName: "البحرين",
    status: "assigned",
  },
  {
    alpha2: "MR",
    alpha3: "MRT",
    countryCallingCodes: ["+222"],
    currencies: ["MRU"],
    ioc: "MTN",
    languages: ["ar"],
    name: "Mauritania",
    arabicName: "موريتانيا",
    status: "assigned",
  },
  {
    alpha2: "DJ",
    alpha3: "DJI",
    countryCallingCodes: ["+253"],
    currencies: ["DJF"],
    ioc: "DJI",
    languages: ["ar"],
    name: "Djibouti",
    arabicName: "جيبوتي",
    status: "assigned",
  },
  {
    alpha2: "SO",
    alpha3: "SOM",
    countryCallingCodes: ["+252"],
    currencies: ["SOS"],
    ioc: "SOM",
    languages: ["ar"],
    name: "Somalia",
    arabicName: "الصومال",
    status: "assigned",
  },
  {
    alpha2: "KM",
    alpha3: "COM",
    countryCallingCodes: ["+269"],
    currencies: ["KMF"],
    ioc: "COM",
    languages: ["ar"],
    name: "Comoros",
    arabicName: "جزر القمر",
    status: "assigned",
  },
];
