export const AUTH_ERROR_CODES = {
  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_INVALID: "OTP_INVALID",
  OTP_LOCKED: "OTP_LOCKED",
  OTP_DAILY_LIMIT: "OTP_DAILY_LIMIT",
  PHONE_NOT_VERIFIED: "PHONE_NOT_VERIFIED",
  ALREADY_ENROLLED: "ALREADY_ENROLLED",
  NOT_REGISTERED: "NOT_REGISTERED",
  PREFILL_READY: "PREFILL_READY",
  GLOBALLY_BLOCKED: "GLOBALLY_BLOCKED",
  TENANT_MISSING: "TENANT_MISSING",
  INVALID_PHONE: "INVALID_PHONE",
} as const;

export const TENANT_ERROR_CODES = {
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  TENANT_SUSPENDED: "TENANT_SUSPENDED",
  TENANT_MISSING: "TENANT_MISSING",
  TENANT_INACTIVE: "TENANT_INACTIVE",
} as const;
