import ClassesTopbar from "@/components/ClassesTopbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <header className="h-[100px] bg-linear-to-l from-[#0d2237] to-[#20364E]">
        <div className="w-[85%] py-1  mx-auto">
          <ClassesTopbar />
        </div>
      </header>
      {children}
    </div>
  );
}
