import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";
import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const almarai = Almarai({
  subsets: ["latin"],
  variable: "--font-almarai-sans",
  weight: ["300", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${almarai.variable}  antialiased flex flex-col`}
        suppressHydrationWarning
      >
        <NavBar />
        <div className="min-h-[calc(100dvh-80px)] mt-20 grow flex flex-col [&>*]:grow">
          {children}
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
